DROP SEQUENCE IF EXISTS id_seq;
CREATE SEQUENCE id_seq START WITH 1 INCREMENT BY 1;

DROP TABLE IF EXISTS country;
DROP TABLE IF EXISTS fish;
DROP TABLE IF EXISTS jetty;

CREATE TABLE IF NOT EXISTS country
(
    id    INTEGER PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    name  VARCHAR(200) NOT NULL,
    lat  FLOAT NOT NULL,
    lon FLOAT NOT NULL
    );

CREATE TABLE IF NOT EXISTS fish
(
    id    INTEGER PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    name  VARCHAR(200) NOT NULL,
    price  FLOAT NOT NULL
    );

CREATE TABLE IF NOT EXISTS jetty
(
    id    INTEGER PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    name  VARCHAR(200) NOT NULL,
    ships_num SMALLINT NOT NULL,
    capacity INTEGER NOT NULL
    );