DROP TABLE IF EXISTS country;
DROP SEQUENCE IF EXISTS country_id_seq;
CREATE TABLE IF NOT EXISTS country
(
    id    INTEGER PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    name  VARCHAR(200) NOT NULL,
    lat  FLOAT NOT NULL,
    lon FLOAT NOT NULL
    );
CREATE SEQUENCE country_id_seq START WITH 1 INCREMENT BY 1;

DROP TABLE IF EXISTS fish;
DROP SEQUENCE IF EXISTS fish_id_seq;
CREATE TABLE IF NOT EXISTS fish
(
    id    INTEGER PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    name  VARCHAR(200) NOT NULL,
    price  FLOAT NOT NULL
    );
CREATE SEQUENCE fish_id_seq START WITH 1 INCREMENT BY 1;

DROP TABLE IF EXISTS jetty;
DROP SEQUENCE IF EXISTS jetty_id_seq;
CREATE TABLE IF NOT EXISTS jetty
(
    id    INTEGER PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    name  VARCHAR(200) NOT NULL,
    ships_num INTEGER NOT NULL,
    capacity INTEGER NOT NULL
    );
CREATE SEQUENCE jetty_id_seq START WITH 1 INCREMENT BY 1;